name: Verify Golden Files

on:
  push:
  pull_request:
    branches:
      - main

jobs:
  verify:
    name: Verify Golden File Screenshots
    runs-on: macos-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          lfs: true

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'temurin'

      - name: Cache Gradle Packages
        uses: actions/cache@v4
        with:
          path: |
            ~/.gradle/caches
            ~/.gradle/wrapper
          # Create a new cache when the versions file or build scripts change
          key: ${{ runner.os }}-gradle-${{ hashFiles('gradle/libs.versions.toml', '**/*.gradle.kts') }}
          restore-keys: |
            ${{ runner.os }}-gradle-

      - name: Set up Android SDK
        uses: android-actions/setup-android@v3
        with:
          # Install specific SDK components to avoid errors and speed up the process.
          # We specify the exact versions required by the project.
          packages: 'platform-tools platforms;android-36 build-tools;34.0.0'

      - name: Accept Android SDK licenses
        run: yes | ${{ env.ANDROID_HOME }}/cmdline-tools/latest/bin/sdkmanager --licenses

      - name: Set up Gradle
        uses: gradle/actions/setup-gradle@v3

      - name: Make gradlew executable
        run: chmod +x ./gradlew

      - name: Run Roborazzi Verification
        run: ./gradlew :example:verifyRoborazziDebug